#!/bin/bash -xe

# This script is for centos 7

# Run the following commands to install the SaltStack repository and key:

sudo yum install https://repo.saltstack.com/yum/redhat/salt-repo-latest-1.el7.noarch.rpm 

wait

sudo yum clean expire-cache

sudo yum install salt-master
sudo yum install salt-minion
sudo yum install salt-ssh
sudo yum install salt-syndic
sudo yum install salt-cloud
sudo yum install salt-api

wait
sudo systemctl restart salt-minion

exit 0
